title: Macro PUBGMC
description: Macro cho PUBG Tencent Gaming Buddy 100% Không Ban Acc.
show_downloads: true
theme: jekyll-theme-cayman
page.title: Macro PUBGMC
page.content: Macro cho PUBG Tencent Gaming Buddy

github:
  64_url: https://github.com/nvck2002/nvck2002.github.io/releases/download/8.0.4/PUBGMC_win64.zip
  32_url: https://github.com/nvck2002/nvck2002.github.io/releases/download/8.0.4/PUBGMC_win32.zip
