title: Macro PUBGMC
description: Macro cho PUBG Tencent Gaming Buddy 100% Không Ban Acc.
show_downloads: true
theme: jekyll-theme-cayman
page.title: Macro PUBGMC
page.content: Macro cho PUBG Tencent Gaming Buddy

github:
  zip_url: https://github.com/nvck2002/PUBGMC/releases/download/8.0/PUBGMC.v8.0.zip
